package net.cybertekt.render;

import net.cybertekt.asset.shader.OGLShader;
import net.cybertekt.exception.OGLException;
import net.cybertekt.math.Vec4f;
import org.lwjgl.opengl.GL20;
import static org.lwjgl.opengl.GL20.GL_COMPILE_STATUS;
import static org.lwjgl.opengl.GL20.GL_LINK_STATUS;
import static org.lwjgl.opengl.GL20.GL_VALIDATE_STATUS;
import static org.lwjgl.opengl.GL20.glAttachShader;
import static org.lwjgl.opengl.GL20.glCreateProgram;
import static org.lwjgl.opengl.GL20.glDeleteProgram;
import static org.lwjgl.opengl.GL20.glDetachShader;
import static org.lwjgl.opengl.GL20.glGetProgrami;
import static org.lwjgl.opengl.GL20.glGetShaderi;
import static org.lwjgl.opengl.GL20.glGetUniformLocation;
import static org.lwjgl.opengl.GL20.glLinkProgram;
import static org.lwjgl.opengl.GL20.glUseProgram;
import static org.lwjgl.opengl.GL20.glValidateProgram;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * OGL Shader - (C) Cybertekt Software
 *
 * Represents an OpenGL shader program that consist of at least one
 * {@link OGLShader GLSL shader}.
 *
 * @author Andrew Vektor
 * @version 1.0.0
 * @since 1.0.0
 */
public class OGLShaderProgram {

    /**
     * Static {@link org.slf4j.Logger logger} for class debugging.
     */
    public static final Logger log = LoggerFactory.getLogger(OGLShaderProgram.class);

    /**
     * The OpenGL shader program identifier. The value of this constant is
     * generated by OpenGL via glCreateProgram.
     */
    private final int id;

    /**
     * Human readable identifier for this shader program.
     */
    private final String name;

    /**
     *
     * @param name the String that identifiers the shader program.
     * @param shaders the {@link OGLShader OGL shaders} to include in this
     * shader program.
     * @throws OGLException
     */
    public OGLShaderProgram(final String name, final OGLShader... shaders) throws OGLException {
        this.id = glCreateProgram();
        this.name = name;

        /* Create GLSL Shader Program */
        if (id == 0) {
            throw new OGLException("Unable to create additional shaders.");
        }

        /* Compile and Attach Shaders */
        for (final OGLShader s : shaders) {

            /* Check Shader Compilation Status */
            if (glGetShaderi(s.getId(), GL_COMPILE_STATUS) == 0) {
                s.compile();
            }
            glAttachShader(id, s.getId());
        }

        /* Link Shader Program */
        glLinkProgram(id);
        if (glGetProgrami(id, GL_LINK_STATUS) == 0) {
            throw new OGLException("Unable to link shaders: " + GL20.glGetProgramInfoLog(id));
        }

        /* Detach Shaders To Free Them For Future Use */
        for (final OGLShader s : shaders) {
            glDetachShader(id, s.getId());
            s.delete();
        }
    }

    /**
     * Validates the shader program. Shader program validation requires
     * significant processing time and should only be used for the purpose of
     * debugging. Validation is not required for a shader program to function
     * properly.
     */
    public final void validate() {
        glValidateProgram(id);
        if (glGetProgrami(id, GL_VALIDATE_STATUS) == 0) {
            log.error("{} Shader Validation Failed: {}", name, GL20.glGetProgramInfoLog(id));
        } else {
            log.info("{} Shader Validation Successful  ", name);
        }
    }

    public final void setUniform(final String name, final Vec4f value) {
        int loc = glGetUniformLocation(id, name);
        if (loc > -1) {
            log.info("Uniform {} Not Found", name);
        } else {
            log.info("Uniform {} Location Is {}", name, loc);
        }
    }

    public final void bind() {
        glUseProgram(id);
    }

    public final void unbind() {
        glUseProgram(0);
    }

    public final void destroy() {
        unbind();
        if (id != 0) {
            glDeleteProgram(id);
        }
    }

    public final int getId() {
        return id;
    }

    public final String getName() {
        return name;
    }

}
